### ISSUE TITLE
Tracking Issue: Initial Release 

### ISSUE THREAD

**Issue by palday** [beacon-biosignals/PyMNE.jl#2]
As part of the Julia industry Contributhon, we're going to package and release our code for interfacing with MNE-Python from Julia. Hooray! Here's what needs to happen. 

Task list
- [x] Make this tracking issue :) 
- [x] No private info in code 
- [x] Pre-make public commit:
  - [x] Add MIT license
  - [x] Add tests + CI badge to README
 - [x] Make sure repo follows best-practice settings
  -  [x] ~Make docs build~
   - [x] ~Add docs badges to README~ 
   - [x] Just document usage in the README
  - [x] Add TagBot GitHub Action
  - [x] Add CompatHelper GitHub Action
- [x] Make repo public
- [x] Have @jrevels enable repo access for the general julia registrator
- [x] Open [PR in Julia registry](https://github.com/JuliaRegistries/General/pull/26361) 
  - [x] Wait for it to auto-merge
